# Imputation - Titanic Dataset

In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv('4_Imputation_Titanic.csv')
df.head()

   survived  pclass     sex   age embarked
0         0       2  female  64.7        C
1         1       3    male  78.8        C
2         0       2    male  60.6        C
3         0       3  female  32.1        S
4         0       1  female  47.7        C

In [3]:
df.isnull().sum()

survived     0
pclass       0
sex          0
age         40
embarked     5
dtype: int64

In [4]:
age_fill = SimpleImputer(strategy='median')
df['age'] = age_fill.fit_transform(df[['age']])
print('filled age with:', age_fill.statistics_)

filled age with: [44.2]

In [5]:
embarked_fill = SimpleImputer(strategy='most_frequent')
df['embarked'] = embarked_fill.fit_transform(df[['embarked']]).ravel()
print('filled embarked with:', embarked_fill.statistics_)

filled embarked with: ['S']

In [6]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
embarked    0
dtype: int64

In [7]:
df.head(10)

   survived  pclass     sex   age embarked
0         0       2  female  64.7        C
1         1       3    male  78.8        C
2         0       2    male  60.6        C
3         0       3  female  32.1        S
4         0       1  female  47.7        C
5         0       2    male  53.2        S
6         0       2    male  44.2        C
7         0       1    male  44.0        S
8         1       3    male  57.0        S
9         1       2    male  14.2        S